fix: update metrics-server to remove CVEs
Azure/AgentBaker pull request #3075
Opened 2023-04-20 00:01 UTC by ganeshkumar5699

**What type of PR is this?**
/kind fix

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

2023-04-20 21:14 UTC, nirnaymsft requested changes
I don't think we can remove v0.5.2 from this list, as Kubernetes version 1.22 will still be using it.

2023-04-20 21:44 UTC, ganeshkumar5699 commented
> I don't think we can remove v0.5.2 from this list, as Kubernetes version 1.22 will still be using it.

k8s 1.22 is not being supported by AKS, so I assume it's ok to remove it?

2023-04-26 00:31 UTC, ganeshkumar5699 commented
@nirnaymsft since you confirmed offline that my original change is still needed, could you please update your review? Thanks

2023-04-26 04:49 UTC, nirnaymsft approved these changes

2023-04-26 17:54 UTC, alexeldeib approved these changes

2023-04-26 21:05 UTC, merged