feat: update Windows base images to 2024.05B
Azure/AgentBaker pull request #4400
Opened 2024-05-15 04:28 UTC by ShiqianTao

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

- WS2019: [May 14, 2024—KB5037765 (OS Build 17763.5820)](https://support.microsoft.com/en-us/topic/may-14-2024-kb5037765-os-build-17763-5820-82d1aefb-093c-4e4a-a729-cd4a829750ad)
- WS2022: [May 14, 2024—KB5037782 (OS Build 20348.2461)](https://support.microsoft.com/en-us/topic/may-14-2024-kb5037782-os-build-20348-2461-e4109269-b248-49cc-84fb-c2d0e2c86b36)
- WS23H2: [May 14, 2024—KB5037781 (OS Build 25398.887)](https://support.microsoft.com/en-us/topic/may-14-2024-kb5037781-os-build-25398-887-c10d3156-5ea0-41b7-a754-8ae1463ecc78)

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

2024-05-15 05:09 UTC, AbelHu approved these changes
LGTM. Thanks for the help.

2024-05-15 09:18 UTC, andyzhangx approved these changes
lgtm in azuredisk-csi image version removal

2024-05-16 00:39 UTC, AbelHu commented on vhdbuilder/packer/generate-windows-vhd-configuration.ps1
> +    # CNS (Container Networking Service) Owner: jaer-tsun (Jaeryn) # aks-rp/toggles/global/azure-cni-cns-windows.yaml
please delete the comment

2024-05-16 00:40 UTC, AbelHu requested changes
Added some comments

2024-05-16 00:42 UTC, AbelHu commented on vhdbuilder/packer/generate-windows-vhd-configuration.ps1
> -    "mcr.microsoft.com/oss/kubernetes/azure-cloud-node-manager:v1.26.22", # for k8s 1.26.x
keep 1.26

2024-05-16 00:53 UTC, ShiqianTao commented on vhdbuilder/packer/generate-windows-vhd-configuration.ps1
> -    "mcr.microsoft.com/oss/kubernetes/azure-cloud-node-manager:v1.26.22", # for k8s 1.26.x
recovered it, thank you

2024-05-16 00:53 UTC, ShiqianTao commented on vhdbuilder/packer/generate-windows-vhd-configuration.ps1
>          $global:imagesToPull = @(
yes, 23h2 has pre-installed the msu

2024-05-16 00:54 UTC, ShiqianTao commented on vhdbuilder/packer/generate-windows-vhd-configuration.ps1
> +    # CNS (Container Networking Service) Owner: jaer-tsun (Jaeryn) # aks-rp/toggles/global/azure-cni-cns-windows.yaml
deleted, thank you.

2024-05-16 04:09 UTC, AbelHu approved these changes
LGTM. Thanks for the PR

2024-05-16 04:34 UTC, merged